#!/bin/bash

# Exit on error
#set -e

# Display Commands/dev-mode
# set -x

# Take host as an argument:
HOST=$1

# Get target and login information from environment.
# Idea for the future: consume stub directly?
USERNAME=$ADMIN_USERNAME
PASSWORD=$ADMIN_PASSWORD
API=$CF_API

# Set CF to use a seperate config file 
export CF_HOME=~/tmp/interroroute

# login with admin credentials
cf api $API > /dev/null
cf auth $USERNAME $PASSWORD > /dev/null

# create routes.json
cf curl /v2/routes > ~/tmp/interroroute/routes.json

# stub of above for development tests:
## touch ~/tmp/interroroute/routes.json
## cp ~/workspace/interrogator/example-output/routes.json ~/tmp/interroroute/routes.json

# pull out an array of hosts with the given host name
jq '.resources | map(select(.entity.host == "nodeHost"))' ~/tmp/interroroute/routes.json > ~/tmp/interroroute/target-routes.json

### NOTE: This is the section that needs to go inside an iterator in the case of multiple matches.

# get a signle entity
jq '.[0].entity' ~/tmp/interroroute/target-routes.json > $CF_HOME/single-entity.json

# assign URLs for curling
APPS_URL=$(jq '.apps_url' ~/tmp/interroroute/single-entity.json | sed -e 's/^"//'  -e 's/"$//')
SPACE_URL=$(jq '.space_url' ~/tmp/interroroute/single-entity.json | sed -e 's/^"//'  -e 's/"$//')
DOMAIN_URL=$(jq '.domain_url' ~/tmp/interroroute/single-entity.json | sed -e 's/^"//'  -e 's/"$//')
ORG_URL=$(cf curl $SPACE_URL | jq '.entity | .organization_url' | sed -e 's/^"//'  -e 's/"$//')

# get the things actual names, and the org
APPS=$(cf curl $APPS_URL | jq '.resources | .[0] | .entity | .name' -r)
### Note: this only yeilds the first such app, needs to be expanded to iterate.
SPACE=$(cf curl $SPACE_URL | jq '.entity | .name' -r)
ORG=$(cf curl $ORG_URL | jq '.entity | .name' -r)
DOMAIN=$(cf curl $DOMAIN_URL | sed '$d' | jq '.entity | .name' -r)

# output results
echo "Apps: $APPS"
echo "Space: $SPACE"
echo "Org: $ORG"
echo "Domain: $DOMAIN"


# logout the admin user
# cf logout