#!/bin/bash

# Exit on error
set -e

# Display Commands/dev-mode
# set -x

# Take app name as an argument:
NAME=$1
ORG=$2
SPACE=$3

# Set CF to use a seperate config file 
export CF_HOME=/tmp/interrogator

# Login and target the app's space
cf api api.staging.cf-app.com > /dev/null
cf auth interrogator interrogator > /dev/null
cf target -o $ORG -s $SPACE > /dev/null

# Get the app's name, instances, quota, and routes
# and store them as json
CF_TRACE=true cf app $NAME | grep ',"name":' > /tmp/interrogator/app.json

# Assign them to env vars
# Core Maifest Attributes:
INTERROGATOR_APP_NAME=$(jq -r '.name' /tmp/interrogator/app.json)
# Saved for posterity so you can see how insane this was before going after the JSON:
# INTERROGATOR_INSTANCES=$(grep instances: /tmp/interrogator/interrogator_cf_app_with_trace.txt | awk '{print substr ($0,length,1)}')
# Now the sane way:
INTERROGATOR_INSTANCES=$(jq '.instances' /tmp/interrogator/app.json)
INTERROGATOR_MEMORY=$(jq '.memory' /tmp/interrogator/app.json)
INTERROGATOR_DISK=$(jq '.disk_quota' /tmp/interrogator/app.json)
INTERROGATOR_HOST=$(jq '.routes' /tmp/interrogator/app.json | jq '.[0] | .host')
INTERROGATOR_DOMAIN=$(jq '.routes' /tmp/interrogator/app.json | jq '.[0] | .domain.name')

# Optional Manifest Attributes:
INTERROGATOR_COMMAND=$(jq '.command' /tmp/interrogator/app.json)

# Initialize a manifest file and write the app details to it
INTERROGATOR_MANIFEST=/tmp/interrogator/$INTERROGATOR_APP_NAME-manifest.yml
#Core manifest attributes:
echo '---' > $INTERROGATOR_MANIFEST
echo 'applications:' >> $INTERROGATOR_MANIFEST
echo "- name: $INTERROGATOR_APP_NAME" >> $INTERROGATOR_MANIFEST
echo "  instances: $INTERROGATOR_INSTANCES" >> $INTERROGATOR_MANIFEST
echo "  memory: ${INTERROGATOR_MEMORY}M" >> $INTERROGATOR_MANIFEST
echo "  disk_quota: ${INTERROGATOR_MEMORY}M" >> $INTERROGATOR_MANIFEST
echo "  host: $INTERROGATOR_HOST" >> $INTERROGATOR_MANIFEST
echo "  domain: $INTERROGATOR_DOMAIN" >> $INTERROGATOR_MANIFEST

#Optional manifest attributes:
if [[ $INTERROGATOR_COMMAND != null ]]; then
    echo "  command: $INTERROGATOR_COMMAND" >> $INTERROGATOR_MANIFEST
fi

# Output created manifest
cat $INTERROGATOR_MANIFEST
